module.exports = {
  testEnvironment: 'node',
  roots: ['<rootDir>/tests'],
  setupFilesAfterEnv: ['<rootDir>/tests/setupAfterEnv.js'],
  detectOpenHandles: true,
  forceExit: true,
  verbose: true,
  testTimeout: 30000,
  collectCoverage: true,
  collectCoverageFrom: [
    '**/*.js',
    '!tests/**/*.js',
    '!scripts/**/*.js',
    '!migrations/**/*.js',
    '!node_modules/**',
    '!coverage/**',
    '!server.js',
    '!config/db.js',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json-summary'],
  coverageThreshold: {
    global: {
      statements: 5,
      branches: 5,
      functions: 5,
      lines: 5,
    },
  },
  moduleFileExtensions: ['js', 'json'],
  testMatch: ['**/?(*.)+(spec|test).[jt]s?(x)'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/coverage/',
    // Non-test scripts in tests/ directory (confirmed via Phase 0 read):
    '/tests/check-descriptions\\.js$',
    '/tests/check-schema\\.js$',
    '/tests/generate-descriptions\\.js$',
    '/tests/phase4-monitoring-test\\.js$',
    '/tests/phase5-advanced-test\\.js$',
    '/tests/queue-now-serving-auto-advance-test\\.js$',
    '/tests/reproduction-stock-cache-bug\\.js$',
    '/tests/simple-bg-test\\.js$',
    '/tests/stock-cache-bug-simple\\.js$',
    '/tests/test-auto-predictive-and-bg-removal\\.js$',
    '/tests/test-background-removal-api\\.js$',
    '/tests/test-background-removal\\.js$',
    '/tests/test-comprehensive-autocomplete\\.js$',
    '/tests/test-enhanced-autocomplete\\.js$',
    '/tests/test-improved-background-removal\\.js$',
    '/tests/test-webp-background-removal\\.js$',
    // Setup files (not tests):
    '/tests/setup\\.global\\.js$',
    '/tests/setupAfterEnv\\.js$',
    '/tests/teardown\\.global\\.js$',
  ],
  globalSetup: '<rootDir>/tests/setup.global.js',
  globalTeardown: '<rootDir>/tests/teardown.global.js',
};


